
#delete database if exists
drop database ride;

#database creation
CREATE DATABASE ride;
use ride;

#user table 

CREATE TABLE ride.USER (
  USER_ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  NAME varchar(20) NOT NULL DEFAULT '',
  COMPANY_NAME varchar(20) NOT NULL DEFAULT '',
  EMAIL varchar(20) NOT NULL DEFAULT '',
  CONTACT int(20) NOT NULL DEFAULT '0',
  HOME_ADDRESS varchar(100) NOT NULL DEFAULT '',
  OFFICE_ADDRESS varchar(100) NOT NULL DEFAULT '',
  START_TIME_PICKUP varchar(10) NOT NULL DEFAULT '',
  OFFICE_TIME_PICKUP varchar(10) NOT NULL DEFAULT '',
  OFFICE_TIME_DROP varchar(20) DEFAULT NULL,
  COMPANY_JOINED_MONTH varchar(20) DEFAULT NULL,
  COMPANY_JOINED_YEAR varchar(20) DEFAULT NULL,
  HAS_CAR tinyint(1) NOT NULL DEFAULT '0',
  CURRENT_POOL_ACTIVE tinyint(1) NOT NULL DEFAULT '0',
  IS_MOBILE_VERIFIED tinyint(1) NOT NULL DEFAULT '0',
  IS_EMAIL_VERIFIED tinyint(1) NOT NULL DEFAULT '0',
  IS_ACTIVE tinyint(1) NOT NULL DEFAULT '0',
  REGISTER_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  MODIFY_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (USER_ID),
  KEY  (NAME),
  KEY (COMPANY_NAME),
  KEY (EMAIL),
  KEY (CONTACT),
  KEY (START_TIME_PICKUP),
  KEY (OFFICE_TIME_PICKUP),
  KEY (OFFICE_TIME_DROP),
  KEY (HAS_CAR),
  KEY (CURRENT_POOL_ACTIVE),
  KEY (MODIFY_DATE),
  KEY (REGISTER_DATE),
  KEY (IS_ACTIVE)
);

#address table

CREATE TABLE ride.ADDRESS(
ADDRESS_ID BIGINT(20) unsigned NOT NULL AUTO_INCREMENT,
ADDRESS_STREET1 varchar(50) NOT NULL DEFAULT '',
ADDRESS_STREET2 varchar(50) NOT NULL DEFAULT '',
CITY varchar(50) NOT NULL DEFAULT '',
STATE varchar(30) NOT NULL DEFAULT '',
PINCODE varchar(10) NOT NULL DEFAULT '',
LATITUDE varchar(20) NOT NULL DEFAULT '',
LONGITUDE VARCHAR(20) NOT NULL DEFAULT '',
USER_ID BIGINT(20) NOT NULL DEFAULT 0,
MODIFY_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
KEY (ADDRESS_ID),
KEY (ADDRESS_STREET1),
KEY (CITY),
KEY (STATE),
KEY (LATITUDE),
KEY (LONGITUDE),
KEY (USER_ID),
KEY (MODIFY_DATE)
);

#pool table

CREATE TABLE ride.POOL(
POOL_ID bigint(20) unsigned NOT NULL AUTO_INCREMENT, 
IS_ACTIVE tinyint(1) NOT NULL DEFAULT '0',
HOST_USER bigint(20) unsigned NOT NULL DEFAULT 0,
GUEST_USER_1 bigint(20) unsigned NOT NULL DEFAULT 0,
GUEST_USER_2 bigint(20) unsigned NOT NULL DEFAULT 0, 
GUEST_USER_3 bigint(20) unsigned NOT NULL DEFAULT 0,
GUEST_USER_4 bigint(20) unsigned NOT NULL DEFAULT 0,
GUEST_USER_5 bigint(20) unsigned NOT NULL DEFAULT 0,
GUEST_USER_6 bigint(20) unsigned NOT NULL DEFAULT 0,
GUEST_USER_7 bigint(20) unsigned NOT NULL DEFAULT 0,
GUEST_USER_8 bigint(20) unsigned NOT NULL DEFAULT 0,
GUEST_USER_9 bigint(20) unsigned NOT NULL DEFAULT 0,
SOURCE_ADDRESS VARCHAR(50) NOT NULL DEFAULT '',
DESTINATION_ADDRESS VARCHAR(20) NOT NULL DEFAULT '',
START_TIME_PICKUP VARCHAR(20) NOT NULL DEFAULT '00:00',
START_TIME_DROP VARCHAR(20) NOT NULL DEFAULT '00:00',
COMMENTS VARCHAR(100) NOT NULL DEFAULT '',
NUMBER_OF_MEMBERS INTEGER  NOT NULL DEFAULT 0,
MAX_MEMBERS INTEGER  NOT NULL DEFAULT 0,
COST_PER_MONTH INTEGER  NOT NULL DEFAULT 0,
ROUTE_ID BIGINT(20) NOT NULL DEFAULT 0,
CAR_ID BIGINT(20) NOT NULL DEFAULT 0,
IS_AVAILABLE tinyint(1) NOT NULL DEFAULT '0',
MODIFY_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(POOL_ID), 
KEY(IS_ACTIVE),
KEY(HOST_USER),
KEY(GUEST_USER_1),
KEY(GUEST_USER_2),
KEY(GUEST_USER_3),
KEY(GUEST_USER_4),
KEY(GUEST_USER_5),
KEY(GUEST_USER_6),
KEY(GUEST_USER_7),
KEY(GUEST_USER_8),
KEY(GUEST_USER_9),
KEY(START_TIME_PICKUP),
KEY(START_TIME_DROP),
KEY(COST_PER_MONTH),
KEY(ROUTE_ID),
KEY(CAR_ID),
KEY(IS_AVAILABLE),
KEY(MODIFY_DATE)
);

#car table

create table ride.CAR(
CAR_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
USER_ID BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
CAR_NAME VARCHAR(50) NOT NULL DEFAULT '', 
CAR_SEATER INTEGER NOT NULL DEFAULT 0,
PRIMARY KEY (CAR_ID),
KEY (USER_ID),
KEY (CAR_SEATER)
);


#pool transaction table

create table ride.POOL_TRANSACTION(
POOL_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
USER_ID BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
REGISTER_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
MODIFY_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
IS_VALID BOOLEAN NOT NULL DEFAULT 0,
PRIMARY KEY (POOL_ID),
KEY (USER_ID),
KEY (MODIFY_DATE),
KEY (REGISTER_DATE)
);

#request table 

create table ride.REQUEST(
REQUEST_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
REQUEST_FROM INTEGER UNSIGNED NOT NULL DEFAULT 0,
REQUEST_TO INTEGER UNSIGNED NOT NULL DEFAULT 0,
REQUEST_TYPE VARCHAR(10) NOT NULL DEFAULT '',
REQUEST_STATUS VARCHAR(15) NOT NULL DEFAULT '',
COMMENTS VARCHAR(100) NOT NULL DEFAULT '',
MODIFY_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (REQUEST_ID),
KEY (REQUEST_FROM),
KEY (REQUEST_TO),
KEY (REQUEST_TYPE),
KEY (MODIFY_DATE),
KEY (REQUEST_STATUS)
);

#request Api Table

CREATE TABLE ride.REQUESTAPI (
  DEVICE_ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  API_KEY varchar(60) NOT NULL DEFAULT '',
  REGISTER_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  MODIFY_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ACTIVATED enum('Y','N') DEFAULT NULL,
  PRIMARY KEY (DEVICE_ID),
  KEY (MODIFY_DATE),
  KEY (REGISTER_DATE)
);



